name: Build

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node_version: 21.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Test secrets
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: test
        run: |
          import os
          data = open("file", "w")
          for q in (os.getenv("MY_VAL")):
            print(q)
            data.write(q)
        shell: bash
        env:
          MY_VAL: ${{ secrets.TEST_SECRET }}

