name: Release

permissions:
  contents: read
  id-token: write

on:
  push:
    tags: v*

jobs:
  release:
    name: Release workflow

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://npm.pkg.github.com"

      - name: Install
        run: yarn --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Test
        run: yarn test

      - name: Publish latest
        if: "!contains(github.ref, '-')"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish next
        if: contains(github.ref, '-')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Remove next tag
        if: "!contains(github.ref, '-')"
        run: npm dist-tag rm thelounge next || true
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
